version: "3"

services:
  codesync:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "<your_docker_username>/codesync"
    ports:
      - "5000:5000"
      - "3000:3000"
      - "8000:8000"